import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(656 reviews)",
    prevPrice: "Rs.1400",
    newPrice: "1000",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71SncdCQuhL._SX679_.jpg",
    title: "Nike Black-White sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(456 reviews)",
    prevPrice: "Rs.1100",
    newPrice: "500",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
 


  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(67 reviews)",
    prevPrice: "Rs.1600",
    newPrice: "1500",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51iKVzwbL6L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Mens CNVS Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(564 reviews)",
    prevPrice: "Rs.1390",
    newPrice: "1000",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51elOaMZtwL._SY695_.jpg",
    title: "Nike Borough Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1421 reviews)",
    prevPrice: "Rs.999",
    newPrice: "500",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61dEMWS+mNL._SX695_.jpg",
    title: "Nike Elevate Sports",
    star: <AiFillStar className="rating-star" />,
    reviews: "(578 reviews)",
    prevPrice: "Rs.8790",
    newPrice: "2000",
    company: "Nike",
    color: "white",
    category: "sports",
  },
  {
    img: "https://m.media-amazon.com/images/I/711b2sDuQcL._SX695_.jpg",
    title: "Nike Kd Trey Sports",
    star: <AiFillStar className="rating-star" />,
    reviews: "(897 reviews)",
    prevPrice: "Rs.7999",
    newPrice: "2000",
    company: "Nike",
    color: "black",
    category: "sports",
  },
  {
    img: "https://m.media-amazon.com/images/I/51QQVPejZhL._SY695_.jpg",
    title: "Nike Elevate III Sports",
    star: <AiFillStar className="rating-star" />,
    reviews: "(868 reviews)",
    prevPrice: "Rs.6780",
    newPrice: "1900",
    company: "Nike",
    color: "black",
    category: "sports",
  },
  {
    img: "https://m.media-amazon.com/images/I/61Uo-VtmD4L._SY695_.jpg",
    title: "Nike Sports",
    star: <AiFillStar className="rating-star" />,
    reviews: "(868 reviews)",
    prevPrice: "Rs.5700",
    newPrice: "1400",
    company: "Nike",
    color: "red",
    category: "sports",
  },
  {
    img: "https://m.media-amazon.com/images/I/51Z2PQ+0LFL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Nike Offcourt Slipper",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.5700",
    newPrice: "1400",
    company: "Nike",
    color: "blue",
    category: "slippers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51zi6Z1p0qL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Nike ADJUST SLIPPER",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.5700",
    newPrice: "1400",
    company: "Nike",
    color: "black",
    category: "slippers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Adidas Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.5000",
    newPrice: "1340",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61ir0SduwZL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Adidas Pace Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.4000",
    newPrice: "2000",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pGKDiw16L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Adidas Grand Sneakers ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.7900",
    newPrice: "3000",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71FCxUGXv5L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Adidas I-CLOUD-3 SLIPPER ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.2000",
    newPrice: "1000",
    company: "Adidas",
    color: "black",
    category: "slippers",
  },
  {
    img: "https://m.media-amazon.com/images/I/41-+auJdoRL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Adidas SLIPPER",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.7900",
    newPrice: "3000",
    company: "Adidas",
    color: "white",
    category: "slippers",
  },  
  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Freak Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.2000",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Adidas Men's Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.1500",
    newPrice: "2000",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81PvHpXJX2L._AC_UL480_FMwebp_QL65_.jpg",
    title: "PUMA BLACK-OCE Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.2000",
    newPrice: "1500",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.1500",
    newPrice: "1000",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.6000",
    newPrice: "2000",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/510JdT-U6nL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Puma Viz Sports",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.4000",
    newPrice: "1500",
    company: "Puma",
    color: "white",
    category: "sports",
  },
  {
    img: "https://m.media-amazon.com/images/I/51ryh-r0OvL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Mens Running Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.4900",
    newPrice: "1200",
    company: "Puma",
    color: "black",
    category: "sports",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.5900",
    newPrice: "1500",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Doubleknit Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.6980",
    newPrice: "2400",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61Jnq4vkHHL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Fusion Evo Golf Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.3900",
    newPrice: "1000",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51pkWSefCNL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Puma Ketava Slipper",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.450",
    newPrice: "390",
    company: "Puma",
    color: "black",
    category: "slippers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61mhJ1uLlOL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Puma Divecat Slippers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.600",
    newPrice: "520",
    company: "Puma",
    color: "blue",
    category: "slippers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.3500",
    newPrice: "1000",
    company: "Vans",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51t-qlu4PtL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Vans Flip Slipper",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.600",
    newPrice: "300",
    company: "Vans",
    color: "black",
    category: "slippers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51en17b2j-L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Vans Unisex Slipper",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.700",
    newPrice: "350",
    company: "Vans",
    color: "black",
    category: "slippers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.1400",
    newPrice: "1000",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51bYbyYrOYL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Mens OxfordMule Formals",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.4099",
    newPrice: "2000",
    company: "Hush Puppies",
    color: "black",
    category: "formals",
  },
  {
    img: "https://m.media-amazon.com/images/I/716mGZCHy9L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Ronnie Leather Formals ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.3099",
    newPrice: "1500",
    company: "Clarke",
    color: "black",
    category: "formals",
  },
  {
    img: "https://m.media-amazon.com/images/I/51AgQkVEF0L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Formal ShoesOxford Formals",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.2999",
    newPrice: "1500",
    company: "vans",
    color: "black",
    category: "formals",
  },
  {
    img: "https://m.media-amazon.com/images/I/4116Hgtv7PL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Zavinio Black Leather Formals ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "Rs.8000",
    newPrice: "2000",
    company: "Bugatti",
    color: "black",
    category: "formals",
  },

];

export default data;